### ISSUE TITLE
Escape does nothing

### ISSUE THREAD

**Issue by gsantner** [jaszhix/Cinnamenu#11]
On 3.0.1 the pressing the escape key does nothing while the menu is open. I expected it 

* to clear search input (if there is any, else skip this)
* close menu

**Comment by schwukas** [comment]
I was lacking this functionality as well so I dug through the code and found a quick and dirty solution. I don't think, this is very well suited for an actual release (even though I didn't experience any issues with it so far) but it works for now.

In the main **applet.js** file (under _.local/share/cinnamon/applets/Cinnamenu@json_) I edited the unused "case statement" in line **1669** and added the function call "**resetSearch();**" which closes the Menu regardless whether something has already been typed in or not. I guess one could tweak that to remove the search term on the first key press and close the menu on the second one but I used this setting on the original Cinnamon menu and that worked fine for me.

Hope that helps :)

**Comment by jaszhix** [comment]
Ah, that case statement is just additive to the list in that condition, so Clutter.KEY_Escape and Clutter.Escape will both trigger that block of logic. Its being used there to allow closing open context menus with escape. I'll fix this issue in the next release.
