### ISSUE TITLE
Allow to set special positions for Cinnamenu specific category items

### ISSUE THREAD

**Issue by gsantner** [jaszhix/Cinnamenu#12]
Currently there is no way to change the position of Bookmark, Places, Favourites, All applications, settings, usermenu (login, logout, details ,..) options. (Not the order of the items inside, but the "special menu categories")

It would be great if these could be orded custom. I use Cinnamenu e.g. from the top, where Bookmarks on top feels bad, and recent items would help me a lot. Currently I e.g. have to go very down to get to these.

![bildschirmfoto vom 2017-10-11 22-53-37](https://user-images.githubusercontent.com/6735650/31466316-0d2768e4-aed7-11e7-88b3-6e105dbcd2b9.png)

**Comment by jaszhix** [comment]
Favorites can be re-ordered, you simply drag and drop those. Bookmarks would require interfacing with each browser to actually index the bookmarks in that order - the only way to do that is manipulating raw JSON, or in Firefox's case sqlite (nope). I think its a bit extreme for an application menu. I won't say it won't ever happen, but its not on the priority list. The same similarly applies to other types of items - places cannot be re-ordered, they are controlled by Nemo. Cinnamenu would be taking the role of several other applications, and I think its out of the scope. Its too much work for not much gain, IMHO.

A more attainable solution might be sorting options, ordering from ascending/descending alphabetically, order by install date (not sure the tracker API has that info).

**Comment by gsantner** [comment]
@jaszhix No, thats not what I meant. It's not about ordering the items inside (the favourites itself), but the menu for it. The thing that says "Favourites".

And about browser: No also here, I didnt meant to reorder the bookmarks itself.. but the "Bookmark" menu option. To have it e.g. on the very bottom

**Comment by jaszhix** [comment]
Okay, that makes more sense. I re-read your post, and I think it could be up for interpretation. ;)

**Comment by gsantner** [comment]
Doing a little update on issue text

**Comment by gsantner** [comment]
@jaszhix Did a little update on issue text

btw: great extension, thanks for working on it! best menu applet I tried so far :D

**Comment by jaszhix** [comment]
Yeah, bookmarks used to be on the bottom, but it took a long time to load and would often slow down cursor selection as soon as the menu opened. The lag doesn't seem to be an issue anymore, so it might be worth defaulting it to the bottom position again.

**Comment by gsantner** [comment]
Oh, thats one of the main reason I thought it would be good to report here :D.

On my machine at least, nope, bookmarks seems a lot of slow right now (lag). Bceause they are on top, near where my cursor is when opening the menu this drove me crazy :D

**Comment by gsantner** [comment]
Also browsing (the already loaded) bookmark list seems quite slow. It is Chrome/ium only right now, or? Or is just my Firefox not saving something as intended?

**Comment by jaszhix** [comment]
What I've noticed on my beefy desktop, and my average laptop, is when the menu first loads, it still takes a bit to load bookmarks depending on how many there are. After that they stay cached and there is no load time until Cinnamon restarts, or the applet restarts. I think keeping track of the category order with drag and drop behavior might be the most user friendly solution, instead of specific options.

**Comment by gsantner** [comment]
Dragn drop of these is even better :D

**Comment by jaszhix** [comment]
Yep. Also, to answer your other question, I think querying Firefox bookmarks is slower because it has to execute SQL queries - where as all the chromium based browsers just use JSON, which is parsed natively in JS.

I primarily use Chrome, so that might be part of the difference.

**Comment by gsantner** [comment]
What about caching this in an own, combined structure?

**Comment by jaszhix** [comment]
Cinnamenu already caches everything, bookmarks are loaded once on initialization, or when the bookmarks option is toggled in the settings. The second thing that can be a slow down factor is rendering hundreds (maybe thousands?) of Clutter actors. I've kept this in mind during refactors and tried to make the menu item classes lighter, but there's still more work to do.

**Comment by gsantner** [comment]
Hmm, it stil seems/feels like they are reloaded everytime I open the menu. But I have to admit that I not will use them anyway (maybe via search, but not the bookmark menu itself)

**Comment by jaszhix** [comment]
Maybe they are better off not being a menu, and just being indexed with search results? I don't find myself using it ever either.

**Comment by gsantner** [comment]
Thats up to you to decide, I have to admit, even if it would be a very appealing UI to browse them I still would use only search to find them

**Comment by jaszhix** [comment]
Well, I don't like removing features, so the bookmarks setting will probably get converted to a dropdown with three options - On, Search Provider, Off.

**Comment by gsantner** [comment]
great  (Y)

@jaszhix Is the pot file uptodate? I can do an lang update for german otherwise now

**Comment by jaszhix** [comment]
Yes, I merged all the PO files with the updated default pot. Thanks.

**Comment by gsantner** [comment]
Ok, tried, but got already 66/66 localized items. There seem to be some non-i18n strings in the application, like "Layout and Content"

**Comment by jaszhix** [comment]
I think the strings in settings-schema.json are all supposed to be picked out by the cinnamon-json-makepot script in `/usr/share/cinnamon`. I ran the script with the --js argument, then ran the files with `msgmerge orig.po Cinnamenu.pot -U`. Not versed in the nuances unfortunately. @Nikokrause is knowledgeable with this stuff, and helped translate the applet originally, so maybe he has an idea.

**Comment by jaszhix** [comment]
Oh, I'm sorry! This repo is way out of date. I've been keeping the ITM repo updated, but this one I've let get behind. You can fork the [cinnamon spices repo](https://github.com/linuxmint/cinnamon-spices-applets), and work from there.

**Comment by gsantner** [comment]
and send PR to which?

**Comment by jaszhix** [comment]
Hm. I'll just update this repo.

Edit: Done. Normally I'd direct people to the spices repo, but this repo should be in sync anyway.

**Comment by NikoKrause** [comment]
The cinnamon-json-makepot --js command should be enough, but not always. E.g. for ITM I did a makepot file because it didn't grabbed all strings.

Not sure in Cinnamenu
