### ISSUE TITLE
Stay in searched item list when using arrow keys

### ISSUE THREAD

**Issue by gsantner** [jaszhix/Cinnamenu#14]
Currently when the search list is open and arrow keys are pressed the next element is chosen from the whole applet's UI. It would be nice if the navigation could stay inside the search results. So when I press e.g. down when the UI is like in image below, it should select `Libreoffice Base` instead of going to the User-Menu on the very bottom left. Also when pressing left on the first item (`Firefox Nightly` in this case) it should jump to the last item, currently it does nothing.

Just an Idea: Maybe the UserMenu can be deactivated completly when search results are shown. Then the tab button could be used to go through the search results.

![bildschirmfoto vom 2017-10-11 23-42-10](https://user-images.githubusercontent.com/6735650/31468378-d35282fa-aedd-11e7-8203-5bfe4b3e52c0.png)

This issue may contain some subjective stuff, but that's what come to me from usability

**Comment by jaszhix** [comment]
Yeah, makes sense, really the cursor shouldn't be stolen by the categories when navigating left since they're disabled.

**Comment by jaszhix** [comment]
~~This is fixed in 3.1.0, I made the first search result highlight which keeps the selection inside the search list.~~

Nope, forgot the category list is disabled.
