### ISSUE TITLE
Favorites position

### ISSUE THREAD

**Issue by accensi** [jaszhix/Cinnamenu#16]
Favorites is the last item. If the panel is on top of screen, to reach any Favorite entry you have to transit over other categories.
Make it configurable, bottom or top of categories list or alterantively, make it just just a icon list on the left,as in the previous incarnation of this applet.

**Comment by jaszhix** [comment]
Icing Task Manager is no longer maintained. I have been wrongly banned from the Linux Mint organization, and not able or willing to contribute any longer.
