### ISSUE TITLE
Question - Theming the app right click menu box

### ISSUE THREAD

**Issue by smurphos** [jaszhix/Cinnamenu#17]
@jaszhix 

Hi,

Can you point in in the right direction of the css Class that controls the theming of the menu box that opens on right click of an app that gives the option to Add to Panel, Add to Desktop etc.....?

It's driving me nuts trying to work it out...

Thanks...

**Comment by jaszhix** [comment]
That is controlled by themes.

[Relevant CSS](https://github.com/linuxmint/Cinnamon/blob/master/data/theme/cinnamon.css#L110).

**Comment by smurphos** [comment]
Thanks  - found the relevant class that was eluding me - .popup-menu-item

**Comment by smurphos** [comment]
Hi @jaszhix 

Sorry to bother you on this again. It looks like the box is inheriting directly from the .menu class.

However it is not rendering a background gradient correctly.... this is my .css...working well elsewhere...

`.menu {
  padding: 10px;
  border: 1px solid #0c1419;
  border-radius: 12px;
  background-gradient-direction: horizontal;
  background-gradient-start: #72a0bf;
  background-gradient-end: #b7c4cc;
  color: #0c1419;
  font-size: 1em;
  min-width: 100px;
}`

what I end up with seems to be a uniform ever so slightly transparent #72a0bf

I notice when changing themes the new theme doesn't always 'take' on the right click box without a cinnamon restart - not sure if that is relevant.

![screenshot from 2018-02-06 06-42-36](https://user-images.githubusercontent.com/29017677/35845153-fa302c6a-0b08-11e8-8539-ad2535a524f1.png)

**Comment by smurphos** [comment]
Almost there - I've got the right-click context menu almost consistent in appearance between cinnamenu, stark menu and the stock menu using this css. Only bugbear remaining is that the padding in `StScrollView.menu-context-menu StBoxLayout` for cinnamenu will not apply top and bottom only left and right. If you are able to point me in the right direction it will save my scalp - lots of head scratching trying to work this out!. I appreciate your busy trying to fix various bits of Cinnamon's applet code at the mo....

```
/*.menu-applications-inner-box StScrollView is the app right click menu*/
/*.menu-favorites-box .menu-context-menu is the app right click menu from the favorites box in the stark menu spices applet*/
.menu-applications-inner-box StScrollView, .menu-context-menu {
    padding: 5px;
    margin: 0.5em 0em;
    border-radius: 10px;
    border: 1px solid #daeaf2;
    background-gradient-direction: vertical;
    background-gradient-start: #28343a;
    background-gradient-end: #577584;
}
/*StScrollView.menu-context-menu is for the right click menu in the cinnamenu spices applet*/
StScrollView.menu-context-menu {
	border-width: 0px;
	padding: 0px;
}
StScrollView.menu-context-menu StBoxLayout {
    padding: 5px;
    background-gradient-direction: vertical;
    background-gradient-start: #28343a;
    background-gradient-end: #577584;
}
```

**Comment by smurphos** [comment]
Workaround 

```
/*.menu-applications-inner-box StScrollView is the app right click menu*/
/*.menu-favorites-box .menu-context-menu is the app right click menu from the favorites box in the stark menu spices applet*/
.menu-applications-inner-box StScrollView, .menu-favorites-box .menu-context-menu {
    padding: 5px;
    margin: 0.5em 0em;
    border-radius: 10px;
    border: 1px solid #daeaf2;
    background-gradient-direction: vertical;
    background-gradient-start: #28343a;
    background-gradient-end: #577584;
}
/*StScrollView.menu-context-menu is for the right click menu in the cinnamenu spices applet*/
StScrollView.menu-context-menu {
	border-width: 0px;
	padding: 0px;
}
StScrollView.menu-context-menu>StBoxLayout {
	padding: 5px;
	border-width: 0px;
    background-gradient-direction: vertical;
    background-gradient-start: #28343a;
    background-gradient-end: #577584;
}
StScrollView.menu-context-menu StBoxLayout>.popup-menu-item {
    margin: 0.2em 0em;
    padding: .3em .7em;
}
.menu-favorites-box StScrollView.menu-context-menu StBoxLayout>.popup-menu-item {
    margin: 0em;
    padding: .5em .7em;

}
```
