### ISSUE TITLE
Feature request -  Cinnamenu specific customStyleClass

### ISSUE THREAD

**Issue by smurphos** [jaszhix/Cinnamenu#19]
Hi Jaszhix,

Would you consider setting an additional Cinnamenu specific customStyleClass in a similar way to the stark menu?

It would make it a lot easier to apply specific Cinnamenu theming when necessary. It's particularly problematic getting the Cinnamenu right click context menu to match the stock menu or stark menu without some css gymnastics and this change would make that a lot less problematic.

Thanks.

Excerpt from the stark menu applet.js......
```
this.menu.setCustomStyleClass('menu-background');
this.menu.setCustomStyleClass("starkmenu-background");
```

**Comment by jaszhix** [comment]
Sure, I could look into that. I have been meaning to fix the context menu styling, since it only looks OK on the Mint themes as far as I can tell.
