### ISSUE TITLE
Setting min-height:  in .menu-application-button causes Cinnamenu rendering error

### ISSUE THREAD

**Issue by smurphos** [jaszhix/Cinnamenu#20]
```
Cinnamon 3.6.7 
Cinnamenu 3.1.3
Intel 2nd Generation Core Processor Family Integrated Graphics Controller
bus-ID: 00:02.0
Display Server: X.Org 1.18.4 drivers: (unloaded: fbdev,vesa)
Resolution: 1366x768@60.03hz
GLX Renderer: Mesa DRI Intel Sandybridge Mobile
GLX Version: 3.0 Mesa 17.2.8 Direct Rendering: Yes
```
Hi - using a theme with a `min-height: 22px; ` set in  `.menu-application-button` & `.menu-application-button-selected` causes Cinnamenu display corruption in grid view.

![screenshot-cinnamon-2018-04-02-053449](https://user-images.githubusercontent.com/29017677/38183477-881b8f6a-3638-11e8-9db3-fc4cd69be72b.png)

**Comment by smurphos** [comment]
Not sure if this helps...

![screenshot-cinnamon-2018-04-02-054802](https://user-images.githubusercontent.com/29017677/38183597-7f496a64-3639-11e8-902b-83cab27d24f1.png)

**Comment by jaszhix** [comment]
It shouldn't be settings the height to 22px, and apparently it is. There is a lot of overrides going on because no theme properly supports grid buttons. This won't change anytime soon unless the styles get into the default Cinnamon CSS.

**Comment by smurphos** [comment]
No worries - it turns out that a min-height for menu-***-buttons  triggers bugs in the display of right click context menus in the stark and stock menus aswell so I've scrapped it.

**Comment by jaszhix** [comment]
Icing Task Manager is no longer maintained. I have been wrongly banned from the Linux Mint organization, and not able or willing to contribute any longer.
