### ISSUE TITLE
Cinnamenu search entry box doesn't expand to allow for theme set padding.

### ISSUE THREAD

**Issue by smurphos** [jaszhix/Cinnamenu#21]
```
Cinnamon 3.6.7 
Cinnamenu 3.1.3
Intel 2nd Generation Core Processor Family Integrated Graphics Controller
bus-ID: 00:02.0
Display Server: X.Org 1.18.4 drivers: (unloaded: fbdev,vesa)
Resolution: 1366x768@60.03hz
GLX Renderer: Mesa DRI Intel Sandybridge Mobile
GLX Version: 3.0 Mesa 17.2.8 Direct Rendering: Yes
```
Hi - a bit of context - I'm experimenting with a theme will the ultimate aim of making it end-user configurable via a companion applet and rebuilding the theme using sassc.  One of the configuration options will be spacing and one of the elements that is modified by spacing is the padding for the menu search entry. It looks like Cinnamenu hardcodes a maximum height for this though so at 'larger' spacing values the text can be cut off.

You might have good reason for this - the 'larger' values I'm testing aren't really suitable for my screen res anyway so it could be that an end user with a greater resolution wouldn't see the same issue with the same theme.

The pic below is with a theme were the #menu-search-entry set with padding: 8px 10px. For comparison also see a pic of the stock menu with the same theme. Font size in the theme is 1em; My fonts across the board are 10pt.

![screenshot-screen-2018-04-02-062551](https://user-images.githubusercontent.com/29017677/38184539-5282ff84-3640-11e8-95c5-3979efe4cad3.png)

![screenshot-screen-2018-04-02-064315](https://user-images.githubusercontent.com/29017677/38184693-5274e6fa-3641-11e8-9d0a-4211b9aa702b.png)

**Comment by jaszhix** [comment]
Icing Task Manager is no longer maintained. I have been wrongly banned from the Linux Mint organization, and not able or willing to contribute any longer.
