### ISSUE TITLE
List view pane does not expand horizontally to match search entry width.

### ISSUE THREAD

**Issue by smurphos** [jaszhix/Cinnamenu#22]
Cinnamenu version: 3.2.2
Mint 19
Cinnamon version: 3.8.7

Hi,

This issue is present on any theme that set a specific width for `#menu-search-entry`. It's not too distracting on Mint-Y and Mint-X where the 'gap' is fairly minimal, but can be quite offputting for themes that set a large width

Pics below are from Adapta and Mint-Y and demonstrate the issue.  Ideally I think the list view pane should expand if necessary so the scroll bar is always against the right edge of the menu as a whole.

![Adapta](https://i.imgur.com/t0qtbgI.png%20mqsf0TypwMtNvfj)

![Mint-Y](https://i.imgur.com/CLL7Tls.png)

**Comment by jaszhix** [comment]
Icing Task Manager is no longer maintained. I have been wrongly banned from the Linux Mint organization, and not able or willing to contribute any longer.
