### ISSUE TITLE
Cinnamenu doesn't work on Linux Mint 19 and cinnamon 3.8.9

### ISSUE THREAD

**Issue by Hossein52Hz** [jaszhix/Cinnamenu#23]
I am using Linux Mint 19 and cinnamon 3.8.9.
I installed Cinnamenu and restart, but it doesn't work. It shows below message in mouse hover(in the setting-> applets):

This applet contains function calls that could potentially cause Cinnamon to crash or freeze. If you are experiencing crashes or freezing, please try removing it.

**Comment by jaszhix** [comment]
That is just a generic warning applied to any applet that does file I/O. The next step would be to highlight it and click "Add to Panel".
