### ISSUE TITLE
App list highlight padding needs adjustment

### ISSUE THREAD

**Issue by gozonjoedaimar** [jaszhix/Cinnamenu#26]
Category list and app list had different padding which is a bit distracting. Please adjust the padding for app list.

![cinnamenu-update](https://user-images.githubusercontent.com/3996485/50627589-1c2cdf00-0f6f-11e9-8eb5-25f5354da212.jpg)

**Comment by jaszhix** [comment]
Icing Task Manager is no longer maintained. I have been wrongly banned from the Linux Mint organization, and not able or willing to contribute any longer.
