### ISSUE TITLE
Cinnamenu doesn't always show content of categories

### ISSUE THREAD

**Issue by fusentast** [jaszhix/Cinnamenu#27]
Cinnamenu doesn't always show content of categories when mouse pointer hovers over.

Mostly occurring with the "Graphics" menu. (Or any other next to the top placed menu)

I've setup the taskbar at the top, using default Cinnamenu values.

What happen is; I open up Cinnamenu and move the mouse pointer downwards over the categories, first "All applications" and then downwards to "Graphics", but the content isn't always shown, it's still showing the content of "All applications".

I can then move further down to "Internet" and the content of that is shown, and if I move back up to "Graphics" I'm able to view the content there now.
 (Sometimes it skips the next category too, so I have to move the mouse pointer down to the fourth category from the top, and then back up to view content)

![cinnemenu_content](https://user-images.githubusercontent.com/46054972/54087998-50e75900-4359-11e9-9b98-0e2f25d7740b.png)

If I move the mouse pointer up and down through the categories, touching the LM logo when the mouse pointer is at the top, it will sometimes show content of the "next to the top" category and sometimes it needs a little nudge.
If I don't hit the Cinnamenu LM logo when moving the mouse pointer up and down through the categories it shows the content of the categories.
(That is once that the 2. and 3. content menu from the top has already been displayed.)

**Important observations**:
**If I aim the mouse pointer at the category icon then the content is always shown, it only occurs when hovering on the text of the category.**

**But if I select _not to show category icons_ it more often shows the content of the categories as intended when the mouse pointer hovers over the category text**

System:
 * Cinnamon version 4.09
 * Distribution - Mint 19.1 64 bit
 * nvidia gtx 760 driver 390.116
 * Cinnamenu v. 4.1.2

**Comment by fusentast** [comment]
I'm sorry, I forgot to mention that in addition to a panel at the top, I also had a panel on the side with only grouped-window-list. It was setup with intellihide.

I have now removed the side panel and it seems that Cinnamenu is a lot more responsive as described in the OP.

**Comment by jaszhix** [comment]
Icing Task Manager is no longer maintained. I have been wrongly banned from the Linux Mint organization, and not able or willing to contribute any longer.
