### ISSUE TITLE
improve searching

### ISSUE THREAD

**Issue by NikoKrause** [jaszhix/Cinnamenu#4]
The searching is weird.
E.g. I get for `systeminfor` 10 results and for `systeminformation` 12 results.

**Comment by jaszhix** [comment]
The threshold could be tightened but it might cut off valid search results when you're looking up bookmarks.

**Comment by NikoKrause** [comment]
I just find it strange, that I get more results, when the search query gets longer.

**Comment by jaszhix** [comment]
Its using [fuse.js](https://github.com/krisk/Fuse) fuzzy searching and the more characters you add, the more it can match partially.

**Comment by NikoKrause** [comment]
Ah. If you think it's okay, then I can close this issue.

I don't get how the booksmarks in the Cinnamenu work.
I don't see a category `booksmarks`.
Also I don't see `recently used files` in your menu. In other menus I see them.

**Comment by jaszhix** [comment]
Hm, that category box is a vscroll container, try scrolling down on it. But yeah, that's a UI issue.

**Comment by NikoKrause** [comment]
Ah. Okay. I see them, when scrolling. But you don't do that, if you don't know it. A scrollbar would make it visible.
My booksmarks category is empty.

**Comment by NikoKrause** [comment]
Also you could add a "Delete recent files" button.

**Comment by jaszhix** [comment]
Is that a common use case? I could see that being dangerous if you have a lot of recent files - this menu goes over 20 because its using different code than the standard menu. Which might also be affecting performance.

**Comment by jaszhix** [comment]
If you get any errors in ```~/.xsession-errors``` or ```~/.cinnamon/glass.log``` feel free to pastebin them. The empty bookmarks is odd, what browsers do you use?

**Comment by NikoKrause** [comment]
I mean the "Clear list" button like in the original menu.

**Comment by NikoKrause** [comment]
Firefox. Do I need to install something to work?
There are no errors.

**Comment by jaszhix** [comment]
For Firefox you need to install the ```gir1.2-gda-5.0``` package because FF uses sqlite. Chrome/Chromium just store their data in JSON.

**Comment by NikoKrause** [comment]
Thanks. It works now. You should add this info to the README file.

**Comment by jaszhix** [comment]
@NikoKrause Search is fine. Its slow however.
