### ISSUE TITLE
improve grid

### ISSUE THREAD

**Issue by NikoKrause** [jaszhix/Cinnamenu#6]
The icons don't stick to the grid, if less then 5 icons:
See
![screenshot-area-2017-03-11-153106](https://cloud.githubusercontent.com/assets/8415124/23824060/0cfa560c-0670-11e7-8bfc-75ca7aea9f93.png)
Compared to 
![screenshot-area-2017-03-11-153033](https://cloud.githubusercontent.com/assets/8415124/23824062/126d590e-0670-11e7-9a81-9df577848d8a.png)

The buttons are wider. The scale by available space is turned off. I.e. the icon buttons should have a fixed size in every category, no matter how much icons there are in a category.

**Comment by jaszhix** [comment]
@NikoKrause Do you see a way to change the style or actor properties to achieve left aligned icons? I'm guessing the [same x/y_align props](https://github.com/jaszhix/Cinnamenu/blob/4eafb8eda5b3f1d74bfa2242d640e91dda8039f9/buttons.js#L415) assigned St.Align values that give it a grid structure are also causing equal spacing.

**Comment by NikoKrause** [comment]
Sorry, I never understood the align properties. They don't seem to change anything, when I change them. The pro for this stuff is @collinss

**Comment by jaszhix** [comment]
Closing this as I don't agree.
