### ISSUE TITLE
Cinnamenu empty

### ISSUE THREAD

**Issue by mfreeman72** [jaszhix/Cinnamenu#8]
When I open the menu, all I get is a small, empty dropdown rectangle.

Here are the .xsession-errors messages after installation and activation of Cinnamenu:

`(cinnamon:3890): Cjs-WARNING **: JS ERROR: Exception in callback for signal: open-state-changed: TypeError: dir.get_icon(...).get_names is not a function
CategoryListButton.prototype._init@/home/mike/.local/share/cinnamon/applets/Cinnamenu@json/buttons.js:112
CategoryListButton@/home/mike/.local/share/cinnamon/applets/Cinnamenu@json/buttons.js:71
CinnamenuPanel.prototype._display@/home/mike/.local/share/cinnamon/applets/Cinnamenu@json/panel.js:1730
CinnamenuPanel.prototype._onOpenStateToggled@/home/mike/.local/share/cinnamon/applets/Cinnamenu@json/panel.js:157
_emit@resource:///org/gnome/gjs/modules/signals.js:140
PopupMenu.prototype.open@/usr/share/cinnamon/js/ui/popupMenu.js:2327
PopupMenuBase.prototype.toggle_with_options@/usr/share/cinnamon/js/ui/popupMenu.js:2080
CinnamenuButton.prototype.on_applet_clicked@/home/mike/.local/share/cinnamon/applets/Cinnamenu@json/applet.js:122
Applet.prototype._onButtonPressEvent@/usr/share/cinnamon/js/ui/applet.js:270

(cinnamon:3890): Cjs-WARNING **: JS ERROR: Exception in callback for signal: open-state-changed: TypeError: dir.get_icon(...).get_names is not a function
CategoryListButton.prototype._init@/home/mike/.local/share/cinnamon/applets/Cinnamenu@json/buttons.js:112
CategoryListButton@/home/mike/.local/share/cinnamon/applets/Cinnamenu@json/buttons.js:71
CinnamenuPanel.prototype._display@/home/mike/.local/share/cinnamon/applets/Cinnamenu@json/panel.js:1730
CinnamenuPanel.prototype._onOpenStateToggled@/home/mike/.local/share/cinnamon/applets/Cinnamenu@json/panel.js:157
_emit@resource:///org/gnome/gjs/modules/signals.js:140
PopupMenu.prototype.open@/usr/share/cinnamon/js/ui/popupMenu.js:2327
PopupMenuBase.prototype.toggle_with_options@/usr/share/cinnamon/js/ui/popupMenu.js:2080
CinnamenuButton.prototype.on_applet_clicked@/home/mike/.local/share/cinnamon/applets/Cinnamenu@json/applet.js:122
Applet.prototype._onButtonPressEvent@/usr/share/cinnamon/js/ui/applet.js:270`

Here are the glass.log messages after installation and activation of Cinnamenu:

`info t=2017-03-11T16:55:47.087Z Installing settings for Cinnamenu@json
info t=2017-03-11T16:55:47.088Z Settings successfully installed for Cinnamenu@json
info t=2017-03-11T16:55:47.148Z Loaded applet Cinnamenu@json in 119 ms
info t=2017-03-11T16:55:47.153Z Adding systray: unknown (24x24px)
info t=2017-03-11T16:55:47.155Z Adding systray: mintupdate.py (24x24px)
info t=2017-03-11T16:55:47.157Z Hiding systray: network
info t=2017-03-11T16:55:47.159Z Adding systray: steam (24x24px)`

I'm also attaching a screenshot.

![screenshot from 2017-03-09 11-17-32](https://cloud.githubusercontent.com/assets/7842664/23825216/8c9a1234-063a-11e7-9b05-5950b4ae6b49.png)

**Comment by mfreeman72** [comment]
Just an update... with the most recent version, instead of an empty menu rectangle (like the previous post), it's now showing a thin vertical line.

**Comment by jaszhix** [comment]
@mfreeman72 Please try the latest version via Cinnamon Spices. A test fix is in place.
